using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using SadrScales.Integration.Assignments;
using SadrScales.Integration.HotKeys;
using SadrScales.Integration.Items;
using SadrScales.Integration.Stores;

namespace SadrScales.Integration.DemoLab
{
    /// <summary>
    /// Builds reproducible synthetic scenarios. The same options and seed always produce the same data.
    /// </summary>
    public static class SadrDemoScenarioFactory
    {
        #region Constants

        private static readonly string[] ProductNames =
        {
            "Apple", "Orange", "Banana", "Tomato", "Potato",
            "Rice", "Sugar", "Tea", "Cheese", "Cake",
            "Chicken", "Fish", "Dates", "Pistachio", "Coffee"
        };

        #endregion

        #region Public API

        /// <summary>
        /// Creates one deterministic scenario. Random-demo mode should first choose/show a random seed, then call this method.
        /// </summary>
        public static SadrDemoScenario Create(SadrDemoScenarioOptions? options = null)
        {
            SadrDemoScenarioOptions settings = options ?? new SadrDemoScenarioOptions();
            Validate(settings);

            var random = new Random(settings.Seed);
            DateTime referenceDate = new DateTime(2026, 1, 1)
                .AddDays((int)(Math.Abs((long)settings.Seed) % 300L));
            var scenario = new SadrDemoScenario(settings.Seed, referenceDate);

            BuildStores(scenario, settings);
            BuildGroups(scenario, settings);
            BuildItems(scenario, settings, random);
            BuildScales(scenario, settings, random);
            BuildAssignmentsAndMappings(scenario, random);
            BuildGroupHotKeys(scenario);
            BuildInvoices(scenario, settings, random);

            return scenario;
        }

        #endregion

        #region Stores / Groups / Items

        private static void BuildStores(SadrDemoScenario scenario, SadrDemoScenarioOptions settings)
        {
            for (int index = 1; index <= settings.StoreCount; index++)
            {
                scenario.Stores.Add(new SadrStore
                {
                    StoreCode = "DEMO-S" + index.ToString("D2", CultureInfo.InvariantCulture),
                    StoreName = "Demo Store " + index.ToString(CultureInfo.InvariantCulture),
                    Descriptions = "Generated by Sadr Integration DemoLab. Seed=" + scenario.Seed
                });
            }
        }

        private static void BuildGroups(SadrDemoScenario scenario, SadrDemoScenarioOptions settings)
        {
            for (int index = 1; index <= settings.GroupCount; index++)
            {
                scenario.Groups.Add(new SadrItemGroup
                {
                    ItemClassCode = "DEMO-G" + index.ToString("D2", CultureInfo.InvariantCulture),
                    ItemClassName = "Demo Group " + index.ToString(CultureInfo.InvariantCulture),
                    Descriptions = "Generated by Sadr Integration DemoLab. Seed=" + scenario.Seed
                });
            }
        }

        private static void BuildItems(
            SadrDemoScenario scenario,
            SadrDemoScenarioOptions settings,
            Random random)
        {
            for (int index = 1; index <= settings.ItemCount; index++)
            {
                SadrItemGroup group = scenario.Groups[(index - 1) % scenario.Groups.Count];
                int plu = 900000 + index;
                int unit = random.Next(0, 4) == 0 ? 2 : 3;
                int unitPrice = random.Next(2, 401) * 500;
                string product = ProductNames[random.Next(ProductNames.Length)];

                scenario.Items.Add(new SadrItem
                {
                    ItemClassCode = group.ItemClassCode,
                    PluNo = plu,
                    PluUnit = unit,
                    UnitPrice = unitPrice,
                    PluCost = unitPrice * 7 / 10,
                    ItemCode = index.ToString(CultureInfo.InvariantCulture),
                    IndexBarcode = "290" + plu.ToString("D10", CultureInfo.InvariantCulture),
                    ShelfDate = random.Next(0, 31),
                    ShelfDatePrint = random.Next(0, 2),
                    SaleDatePrint = 1,
                    PluName = "Demo " + product + " " + index.ToString("D3", CultureInfo.InvariantCulture),
                    Text1 = "Demo Seed " + scenario.Seed.ToString(CultureInfo.InvariantCulture),
                    DeleteFlag = 0
                });
            }
        }

        #endregion

        #region Scales / Assignments / Mapping / HotKeys

        private static void BuildScales(
            SadrDemoScenario scenario,
            SadrDemoScenarioOptions settings,
            Random random)
        {
            for (int index = 0; index < settings.ScaleCount; index++)
            {
                int scaleId = 81 + index;
                SadrStore store = scenario.Stores[index % scenario.Stores.Count];
                SadrItemGroup primaryGroup = scenario.Groups[index % scenario.Groups.Count];
                string model = random.Next(0, 2) == 0 ? "LSG" : "PLUS";

                scenario.Scales.Add(new SadrDemoScale
                {
                    ScaleId = scaleId,
                    Model = model,
                    IpAddress = "192.0.2." + (11 + index).ToString(CultureInfo.InvariantCulture),
                    Port = 5000,
                    Mac = "02:00:00:00:" +
                        (scenario.Seed & 0xFF).ToString("X2", CultureInfo.InvariantCulture) + ":" +
                        (index + 1).ToString("X2", CultureInfo.InvariantCulture),
                    DeviceName = "Demo Scale " + scaleId.ToString(CultureInfo.InvariantCulture),
                    StoreCode = store.StoreCode,
                    StoreName = store.StoreName ?? string.Empty,
                    PrimaryItemGroupCode = primaryGroup.ItemClassCode,
                    HotKeyCountPerPage = 40,
                    HotKeyPageCount = 3
                });
            }
        }

        private static void BuildAssignmentsAndMappings(SadrDemoScenario scenario, Random random)
        {
            foreach (SadrDemoScale scale in scenario.Scales)
            {
                int primaryIndex = scenario.Groups.FindIndex(
                    group => string.Equals(group.ItemClassCode, scale.PrimaryItemGroupCode, StringComparison.Ordinal));
                var groups = new List<string> { scale.PrimaryItemGroupCode };

                if (scenario.Groups.Count > 1 && random.Next(0, 2) == 1)
                {
                    string second = scenario.Groups[(primaryIndex + 1) % scenario.Groups.Count].ItemClassCode;
                    if (!groups.Contains(second))
                    {
                        groups.Add(second);
                    }
                }

                groups.Sort(StringComparer.Ordinal);
                scenario.ScaleAssignments[scale.ScaleId] = groups;

                List<SadrItem> eligible = scenario.Items
                    .Where(item => groups.Contains(item.ItemClassCode))
                    .OrderBy(item => item.PluNo)
                    .Take(12)
                    .ToList();

                var mappings = new List<SadrScaleItemMap>();
                for (int index = 0; index < eligible.Count; index++)
                {
                    mappings.Add(new SadrScaleItemMap
                    {
                        ScaleId = scale.ScaleId,
                        PluNo = eligible[index].PluNo,
                        ItemCode = index + 1,
                        PageNo = index < 10 ? (int?)0 : null,
                        KeyNo = index < 10 ? (int?)(index + 1) : null
                    });
                }

                scenario.ScaleMappings[scale.ScaleId] = mappings;
            }
        }

        private static void BuildGroupHotKeys(SadrDemoScenario scenario)
        {
            foreach (SadrItemGroup group in scenario.Groups)
            {
                List<SadrItem> items = scenario.Items
                    .Where(item => string.Equals(item.ItemClassCode, group.ItemClassCode, StringComparison.Ordinal))
                    .OrderBy(item => item.PluNo)
                    .Take(10)
                    .ToList();

                var hotKeys = new List<SadrHotKey>();
                for (int index = 0; index < items.Count; index++)
                {
                    hotKeys.Add(new SadrHotKey
                    {
                        PageNo = 0,
                        KeyNo = index + 1,
                        PluNo = items[index].PluNo
                    });
                }

                scenario.GroupHotKeys[group.ItemClassCode] = hotKeys;
            }
        }

        #endregion

        #region Sales / Invoices

        private static void BuildInvoices(
            SadrDemoScenario scenario,
            SadrDemoScenarioOptions settings,
            Random random)
        {
            for (int index = 1; index <= settings.InvoiceCount; index++)
            {
                SadrDemoScale scale = scenario.Scales[(index - 1) % scenario.Scales.Count];
                int fid = 1000 + index;
                DateTime saleDate = scenario.ReferenceDate
                    .AddDays(-random.Next(0, 7))
                    .AddHours(8 + random.Next(0, 12))
                    .AddMinutes(random.Next(0, 60));

                var invoice = new SadrDemoInvoice
                {
                    ScaleId = scale.ScaleId,
                    Fid = fid,
                    SaleDateTime = saleDate,
                    TotalBarcode = "25" +
                        scale.ScaleId.ToString("D3", CultureInfo.InvariantCulture) +
                        fid.ToString("D9", CultureInfo.InvariantCulture),
                    ItemBarcode = "DEMO-I-" + scenario.Seed.ToString(CultureInfo.InvariantCulture) +
                        "-" + index.ToString("D4", CultureInfo.InvariantCulture),
                    IsAcknowledged = index % 5 == 0
                };

                List<SadrScaleItemMap> mappings = scenario.ScaleMappings[scale.ScaleId];
                int lineCount = 1 + random.Next(0, 4);
                for (int lineIndex = 0; lineIndex < lineCount; lineIndex++)
                {
                    SadrScaleItemMap mapping = mappings[(index + lineIndex) % mappings.Count];
                    SadrItem item = scenario.Items.First(candidate => candidate.PluNo == mapping.PluNo);
                    decimal amount = item.PluUnit == 2
                        ? random.Next(1, 6)
                        : Math.Round((decimal)(random.Next(100, 3001) / 1000.0), 3);
                    int linePrice = Math.Max(1, (int)Math.Round(amount * item.UnitPrice, MidpointRounding.AwayFromZero));

                    invoice.Lines.Add(new SadrDemoInvoiceLine
                    {
                        SubId = lineIndex + 1,
                        PluNo = item.PluNo,
                        PluName = item.PluName ?? string.Empty,
                        Unit = item.PluUnit,
                        Amount = amount,
                        UnitPrice = item.UnitPrice,
                        TotalPrice = linePrice
                    });
                }

                scenario.Invoices.Add(invoice);
            }
        }

        #endregion

        #region Validation

        private static void Validate(SadrDemoScenarioOptions options)
        {
            if (options.StoreCount < 1 || options.StoreCount > 20)
                throw new ArgumentOutOfRangeException(nameof(options.StoreCount), "StoreCount must be 1..20.");
            if (options.GroupCount < 1 || options.GroupCount > 20)
                throw new ArgumentOutOfRangeException(nameof(options.GroupCount), "GroupCount must be 1..20.");
            if (options.ItemCount < options.GroupCount || options.ItemCount > 200)
                throw new ArgumentOutOfRangeException(nameof(options.ItemCount), "ItemCount must cover every group and be at most 200.");
            if (options.ScaleCount < 1 || options.ScaleCount > 10)
                throw new ArgumentOutOfRangeException(nameof(options.ScaleCount), "ScaleCount must be 1..10 so demo Scale IDs stay within 81..90.");
            if (options.InvoiceCount < 0 || options.InvoiceCount > 200)
                throw new ArgumentOutOfRangeException(nameof(options.InvoiceCount), "InvoiceCount must be 0..200.");
        }

        #endregion
    }
}
